query Viewer {
  Viewer {
    ...UserInfo
  }
}

fragment UserInfo on User 
@apollo_client_ios_localCacheMutation {
  id
  name
  avatar {
    large
  }
  bannerImage
  about(asHtml: true)
  options {
    profileColor
    displayAdultContent
    staffNameLanguage
    titleLanguage
  }
  mediaListOptions {
    scoreFormat
    animeList {
      advancedScoring
      advancedScoringEnabled # shared between animeList and mangaList
      customLists
      sectionOrder
    }
    mangaList {
      customLists
      sectionOrder
    }
  }
  isFollowing
  isFollower
  donatorBadge
  donatorTier
}
