disabled_rules:
  - comment_spacing
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - todo

excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - AniListAPI
