//
//  StaffRole.swift
//  AniHyou
//
//  Created by Axel Lopez on 22/10/2024.
//

import AniListAPI
import SwiftUI

extension MediaStaff {
    var roleLocalized: LocalizedStringKey? {
        switch role {
        case "A&R Producer": "A&R Producer"
        case "ADR Director": "ADR Director"
        case "Accessory Design": "Accessory Design"
        case "Action Animator": "Action Animator"
        case "Action Director": "Action Director"
        case "Action Animation Director": "Action Animation Director"
        case "Action Animation Supervisor": "Action Animation Supervisor"
        case "Advertising": "Advertising"
        case "Advertising Producer": "Advertising Producer"
        case "Animation Director": "Animation Director"
        case "Animation Producer": "Animation Producer"
        case "Animation Production Assistance":
            "Animation Production Assistance"
        case "Animation Supervisor": "Animation Supervisor"
        case "Animation": "Animation"
        case "Art": "Art"
        case "Art Board": "Art Board"
        case "Art Composition": "Art Composition"
        case "Art Design": "Art Design"
        case "Art Director": "Art Director"
        case "Assistance": "Assistance"
        case "Assistant": "Assistant"
        case "Assistant Animation Director": "Assistant Animation Director"
        case "Assistant Art Director": "Assistant Art Director"
        case "Assistant Chief Animation Director":
            "Assistant Chief Animation Director"
        case "Assistant Chief Director": "Assistant Chief Director"
        case "Assistant Director of Photography":
            "Assistant Director of Photography"
        case "Assistant Director": "Assistant Director"
        case "Assistant Episode Director": "Assistant Episode Director"
        case "Assistant Producer": "Assistant Producer"
        case "Assistant Production Manager": "Assistant Production Manager"
        case "Assistant Unit Director": "Assistant Unit Director"
        case "Associate Producer": "Associate Producer"
        case "Background Art": "Background Art"
        case "Background Art Assistance": "Background Art Assistance"
        case "Background Manager": "Background Manager"
        case "Background Production": "Background Production"
        case "3DCG": "3DCG"
        case "3D Art": "3D Art"
        case "3D Works": "3D Works"
        case "CG Animation Director": "CG Animation Director"
        case "CG Animation": "CG Animation"
        case "CG Assistant Director": "CG Assistant Director"
        case "CG Background Modeling": "CG Background Modeling"
        case "CG Director": "CG Director"
        case "CG Layout": "CG Layout"
        case "CG Modeling Director": "CG Modeling Director"
        case "CG Modeling": "CG Modeling"
        case "CG Producer": "CG Producer"
        case "CG Production": "CG Production"
        case "CG Supervisor": "CG Supervisor"
        case "CG Technical Director": "CG Technical Director"
        case "Character Design": "Character Design"
        case "Chief Animation Director": "Chief Animation Director"
        case "Chief Director": "Chief Director"
        case "Chief Episode Director": "Chief Episode Director"
        case "Chief Mechanical Animation Director":
            "Chief Mechanical Animation Director"
        case "Chief Producer": "Chief Producer"
        case "Chief Production Desk": "Chief Production Desk"
        case "Chief Supervisor": "Chief Supervisor"
        case "Chief Unit Director": "Chief Unit Director"
        case "Co-Producer": "Co-Producer"
        case "Color Coordination": "Color Coordination"
        case "Color Design Assistance": "Color Design Assistance"
        case "Color Design": "Color Design"
        case "Coloring": "Coloring"
        case "Concept Art": "Concept Art"
        case "Costume Design": "Costume Design"
        case "Cover Illustration": "Cover Illustration"
        case "Creature Design": "Creature Design"
        case "Design Assistance": "Design Assistance"
        case "Design Works": "Design Works"
        case "2D Design": "2D Design"
        case "2D Works": "2D Works"
        case "Digital Animation": "Digital Animation"
        case "Digital Art": "Digital Art"
        case "Digital Coloring": "Digital Coloring"
        case "Digital Optical Recording": "Digital Optical Recording"
        case "Digital Paint": "Digital Paint"
        case "Digital Photography": "Digital Photography"
        case "Digital Production Assistant": "Digital Production Assistant"
        case "Director of Photography": "Director of Photography"
        case "Director": "Director"
        case "Editing Assistant": "Editing Assistant"
        case "Editing Manager": "Editing Manager"
        case "Editing": "Editing"
        case "Effects": "Effects"
        case "2D Effects": "2D Effects"
        case "Effects Animation Director": "Effects Animation Director"
        case "Endcard": "Endcard"
        case "Episode Director": "Episode Director"
        case "Episode Director (OP)": "Episode Director (OP)"
        case "Episode Director (ED)": "Episode Director (ED)"
        case "Executive Producer": "Executive Producer"
        case "Executive Supervisor": "Executive Supervisor"
        case "Eyecatch": "Eyecatch"
        case "Finishing Assistance": "Finishing Assistance"
        case "Finishing Check": "Finishing Check"
        case "Finishing Manager": "Finishing Manager"
        case "Finishing Production": "Finishing Production"
        case "Finishing": "Finishing"
        case "Illustration": "Illustration"
        case "HD Editing": "HD Editing"
        case "In-Between Animation Assistance":
            "In-Between Animation Assistance"
        case "In-Between Animation": "In-Between Animation"
        case "In-Betweens Check": "In-Betweens Check"
        case "In-Betweens Manager": "In-Betweens Manager"
        case "Insert Song Performance": "Insert Song Performance"
        case "Insert Song Lyrics": "Insert Song Lyrics"
        case "Insert Song Composition": "Insert Song Composition"
        case "Insert Song Arrangement": "Insert Song Arrangement"
        case "Key Animation": "Key Animation"
        case "1st Key Animation Director": "1st Key Animation Director"
        case "1st Key Assistant Animation Director":
            "1st Key Assistant Animation Director"
        case "2nd Key Animation": "2nd Key Animation"
        case "Key Animation Assistance": "Key Animation Assistance"
        case "Key Animation (OP)": "Key Animation (OP)"
        case "Layout Animation Director": "Layout Animation Director"
        case "Layout Animation Supervisor": "Layout Animation Supervisor"
        case "Layout Editor": "Layout Editor"
        case "Layout Supervisor": "Layout Supervisor"
        case "Layout": "Layout"
        case "Lettering": "Lettering"
        case "Line Producer": "Line Producer"
        case "Literary Arts Assistance": "Literary Arts Assistance"
        case "Literary Arts": "Literary Arts"
        case "Main Animator": "Main Animator"
        case "Mechanical Animation Director": "Mechanical Animation Director"
        case "Mechanical Design": "Mechanical Design"
        case "Mechanical Supervisor": "Mechanical Supervisor"
        case "Monitor Graphics": "Monitor Graphics"
        case "Monster Design": "Monster Design"
        case "Music Arrangement": "Music Arrangement"
        case "Music Assistance": "Music Assistance"
        case "Music Composition": "Music Composition"
        case "Music Director": "Music Director"
        case "Music Lyrics": "Music Lyrics"
        case "Music Performance": "Music Performance"
        case "Music Producer": "Music Producer"
        case "Music Production Assistance": "Music Production Assistance"
        case "Music Production": "Music Production"
        case "Music Selection": "Music Selection"
        case "Music Supervisor": "Music Supervisor"
        case "Music": "Music"
        case "Musical Instrument Supervisor": "Musical Instrument Supervisor"
        case "Offline Editing Manager": "Offline Editing Manager"
        case "Offline Editing": "Offline Editing"
        case "Online Editing Manager": "Online Editing Manager"
        case "Online Editing": "Online Editing"
        case "Online HD Editing": "Online HD Editing"
        case "Optical Recording": "Optical Recording"
        case "Original Character Design": "Original Character Design"
        case "Original Creator": "Original Creator"
        case "Original Illustration": "Original Illustration"
        case "Original Plan": "Original Plan"
        case "Original Story": "Original Story"
        case "Overseas Advertising Producer": "Overseas Advertising Producer"
        case "Paint": "Paint"
        case "Photography Assistance": "Photography Assistance"
        case "Photography Chief": "Photography Chief"
        case "Photography Manager": "Photography Manager"
        case "Photography": "Photography"
        case "Planning Assistance": "Planning Assistance"
        case "Planning Producer": "Planning Producer"
        case "Planning": "Planning"
        case "Producer": "Producer"
        case "Production Assistance": "Production Assistance"
        case "Production Assistant": "Production Assistant"
        case "Production Committee": "Production Committee"
        case "Production Design": "Production Design"
        case "Production Desk": "Production Desk"
        case "Production": "Production"
        case "Prop Design": "Prop Design"
        case "Recording Adjustment": "Recording Adjustment"
        case "Recording Assistant": "Recording Assistant"
        case "Recording Engineer": "Recording Engineer"
        case "Recording": "Recording"
        case "Script": "Script"
        case "Script Assistance": "Script Assistance"
        case "Series Composition": "Series Composition"
        case "Series Composition Assistance": "Series Composition Assistance"
        case "Setting Design": "Setting Design"
        case "Sound Design": "Sound Design"
        case "Sound Director": "Sound Director"
        case "Sound Effects": "Sound Effects"
        case "Sound Effects Assistance": "Sound Effects Assistance"
        case "Sound Producer": "Sound Producer"
        case "Sound Production Manager": "Sound Production Manager"
        case "Sound Production": "Sound Production"
        case "Sound Supervisor": "Sound Supervisor"
        case "Special Design": "Special Design"
        case "Special Effects Assistant": "Special Effects Assistant"
        case "Special Effects": "Special Effects"
        case "Story & Art": "Story & Art"
        case "Story & Illustration": "Story & Illustration"
        case "Story": "Story"
        case "Storyboard": "Storyboard"
        case "Sub Character Design": "Sub Character Design"
        case "Supervisor": "Supervisor"
        case "Supporting Staff": "Supporting Staff"
        case "Technical Director": "Technical Director"
        case "Theme Song Lyrics": "Theme Song Lyrics"
        case "Theme Song Lyrics (OP)": "Theme Song Lyrics (OP)"
        case "Theme Song Lyrics (ED)": "Theme Song Lyrics (ED)"
        case "Theme Song Lyrics (OP, ED)": "Theme Song Lyrics (OP, ED)"
        case "Theme Song Composition": "Theme Song Composition"
        case "Theme Song Composition (OP)": "Theme Song Composition (OP)"
        case "Theme Song Composition (ED)": "Theme Song Composition (ED)"
        case "Theme Song Composition (OP, ED)":
            "Theme Song Composition (OP, ED)"
        case "Theme Song Arrangement": "Theme Song Arrangement"
        case "Theme Song Arrangement (OP)": "Theme Song Arrangement (OP)"
        case "Theme Song Arrangement (ED)": "Theme Song Arrangement (ED)"
        case "Theme Song Arrangement (OP, ED)":
            "Theme Song Arrangement (OP, ED)"
        case "Theme Song Performance": "Theme Song Performance"
        case "Theme Song Performance (OP)": "Theme Song Performance (OP)"
        case "Theme Song Performance (ED)": "Theme Song Performance (ED)"
        case "Theme Song Performance (OP, ED)":
            "Theme Song Performance (OP, ED)"
        case "Title Logo Design Assistance": "Title Logo Design Assistance"
        case "Title Logo Design": "Title Logo Design"
        case "Touch-up Art & Lettering": "Touch-up Art & Lettering"
        case "Touch-up Art": "Touch-up Art"
        case "Translator": "Translator"
        case "Unit Director": "Unit Director"
        case "Video Editing": "Video Editing"
        case "Visual Coordinator": "Visual Coordinator"
        case "Visual Director": "Visual Director"
        case "Visual Effects": "Visual Effects"
        case "World Design": "World Design"
        case "Weapon Design": "Weapon Design"
        default: nil
        }
    }
}
