query MediaChart($page: Int, $perPage: Int, $sort: [MediaSort], $type: MediaType, $status: MediaStatus, $format: MediaFormat, $country: CountryCode) {
  Page(page: $page, perPage: $perPage) {
    media(sort: $sort, type: $type, status: $status, format: $format, countryOfOrigin: $country) {
      id
      title {
        userPreferred
      }
      type
      format
      startDate {
        year
      }
      coverImage {
        large
      }
      meanScore
      status
      genres
      episodes
      chapters
      duration
      mediaListEntry {
        status
      }
      isAdult
    }
    pageInfo {
      ...CommonPage
    }
  }
}
